env:
  browser: true
  es6: true
extends: 'eslint:recommended'
plugins:
  - react
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
